# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('edad', models.IntegerField(default=0)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grado.Grados')),
            ],
        ),
    ]
